### ISSUE TITLE
Milestone: from FBPIC output to HiPACE++ input

### ISSUE THREAD

**Issue by MaxThevenet** [LASY-org/lasy#127]
This needs the following operations:
1. Generate a RZ profile from the output of an FBPIC simulation
2. Convert from RZ to 3D
3. Write 3D output at lasy format
4. Read profile in HiPACE++

This requires the following new capabilities:
- [ ] (required, in lasy) Read input from openPMD file. It is not clear to me whether we should have 1 reader per code or 1 for all openPMD-based files. I would recommend trying the latter, and we could pass a few arguments or just the code name to fix the parameters that may differ between codes (z or t representation, field stored, E vs. a0, RZ vs. 3D, etc.)
- [ ] (required, in lasy) dummy converter z = -c*t. As HiPACE++ currently reverts this operation exactly, that could be a trick to make the this z-to-z pipeline fully accurate and computationally cheap. [Maxence]
- [ ] (required, in lasy, but can rely on openPMD-viewer) Convert from electric field to electric field envelope. [Maxence]
- [ ] Convert from RZ to 3D (this is probably already implemented)

There are other ways to make this work, including supporting RZ input in HiPACE++, but I think it is preferable to do such 
operations in LASY at the moment.
